#!/usr/bin/env bash
# Vagrant Configuration for Ubuntu Server 22.04

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jay-alexander-elliot/ubuntu-22-04"
  config.vm.box_version = "1.1.1"

  config.vm.define "jay-alexander-elliot-ubuntu-22-04-server"
  config.vm.hostname = "jay-alexander-elliot-ubuntu-22-04-server"
  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.101.6"
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "public_network"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.ssh.username = "vagrant"
  config.ssh.private_key_path = ["~
