# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant configuration for Kali Linux Virtual Machine

Vagrant.configure("2") do |config|
  # Use Kali Linux as the base box for Vagrant
  config.vm.box = "kalilinux/rolling"
  config.vm.box_version = "1.1.1"

  # Define virtual machine name.
  config.vm.define "jay-alexander-elliot-kali-linux"

  # Set virtual machine hostname.
  config.vm.hostname = "jay-alexander-elliot-kali-linux"

  # Disable automatic box update checking.
  config.vm.box_check_update = false

  # Network configuration.
  config.vm.network "private_network", ip: "192.168.201.10"

  # SSH credentials to connect to virtual machine.
  config.ssh.username = "vagrant"
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  # Provider-specific configuration.
  config.vm.provider "vmware_fusion" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "1"
  end

  # Provisioning with a shell script.
  config.vm.provision "shell", inline: <<-SHELL
    apt update -y
    apt install -y wget vim net-tools gcc make tar bind-utils nc git unzip sysstat tree
  SHELL
end
