# -*- mode: ruby -*-
# vi: set ft=ruby :

# Ubuntu Server 22.04 Configuration for Vagrant

Vagrant.configure("2") do |config|
  # Define the base box for Ubuntu Server 22.04
  config.vm.box = "jay-alexander-elliot/ubuntu-22-04"
  config.vm.box_version = "1.1.1"

  # Define virtual machine name.
  config.vm.define "jay-alexander-elliot-ubuntu-22-04-server"

  # Set virtual machine hostname.
  config.vm.hostname = "jay-alexander-elliot-ubuntu-22-04-server"

  # Disable automatic box update checking.
  config.vm.box_check_update = false

  # Create a private network, which allows host-only access to the machine using a specific IP.
  config.vm.network "private_network", ip: "192.168.201.6"

  # Share an additional folder to the guest VM.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # SSH credentials to connect to virtual machine.
  config.ssh.username = "vagrant"
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. Example for VMware Fusion:
  config.vm.provider "vmware_fusion" do |vb|
    vb.gui = false  # Disable GUI when booting the virtual machine.
    vb.memory = "2048"  # Allocate memory to the virtual machine.
    vb.cpus = "1"  # Allocate processors to the virtual machine.
  end

  # Enable provisioning with a shell script. 
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt upgrade -y
    apt install -y wget vim net-tools gcc make tar git unzip sysstat tree
  SHELL
end
