#!/usr/bin/env bash
# FreeBSD 13 Vagrant Configuration

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-13.0-RELEASE"
  config.vm.box_version = "2021.04.09"

  # Define virtual machine name.
  config.vm.define "jay-alexander-elliot-freebsd-13-server"

  # Set virtual machine hostname.
  config.vm.hostname = "jay-alexander-elliot-freebsd-13-server"

  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.101.10"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.ssh.username = "vagrant"
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm",:id,"--usb","on"]
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "1"
    vb.name = "jay-alexander-elliot-freebsd-13-server"
  end

  config.vm.provision "shell", inline: <<-SHELL
    pkg update
    pkg upgrade -y
    pkg install -y wget vim net-tools gcc make tar git unzip sysstat tree nano
  SHELL
end
