# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile - Kali Linux Configuration

Vagrant.configure("2") do |config|
  # Define the box from Vagrant Cloud
  config.vm.box = "kalilinux/rolling"
  config.vm.box_version = "2023.4.0"

  # Define virtual machine name
  config.vm.define "jay-alexander-elliot-kali-linux"

  # Set virtual machine hostname
  config.vm.hostname = "jay-alexander-elliot-kali-linux"

  # Disable automatic box update checking
  config.vm.box_check_update = false

  # Define a private network
  config.vm.network "private_network", ip: "192.168.101.10"

  # Disable default synced folder
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # SSH credentials
  config.ssh.username = "vagrant"
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  # Configuration for VirtualBox provider
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "1"
    vb.name = "jay-alexander-elliot-kali-linux"
  end

  # Provision the VM with a shell script
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y
    apt-get install -y wget vim net-tools gcc make tar git unzip sysstat tree nano
  SHELL
end
