#!/usr/bin/env bash
# Vagrant Configuration for jay-alexander-elliot Amazon Linux 2 Server

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jay-alexander-elliot/amazon-linux-2"
  config.vm.box_version = "1.1.1"

  config.vm.define "jay-alexander-elliot-amazon-linux-2-server"
  config.vm.hostname = "jay-alexander-elliot-amazon-linux-2-server"
  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.101.11"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.ssh.username = "vagrant"
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm",:id,"--usb","on"]
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "1"
    vb.name = "jay-alexander-elliot-amazon-linux-2-server"
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum update
    yum upgrade -y
    yum install -y wget vim net-tools gcc make tar git unzip sysstat tree
  SHELL
end
