#!/usr/bin/env bash
# Vagrant Configuration Script


Vagrant.configure("2") do |config|
  config.vm.box_version = "1.1.1"
  
    config.vm.box = "jay-alexander-elliot/alma-linux-9"
  
    # Define virtual machine name.
    config.vm.define "jay-alexander-elliot-alma-linux-9-server"
  
    # Set virtual machine hostname.
    config.vm.hostname = "jay-alexander-elliot-alma-linux-9-server"
  
    config.vm.box_check_update = false
  
    config.vm.network "private_network", ip: "192.168.101.8"
  
    config.vm.synced_folder ".", "/vagrant", disabled: true
  
    # SSH credentials to connect to virtual machine.
    config.ssh.username = "vagrant"
    config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
    config.ssh.insert_key = false
  
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm",:id,"--usb","on"]
      vb.gui = false
      vb.memory = "2048"
      vb.cpus = "1"
      vb.name = "jay-alexander-elliot-alma-linux-9-server"
    end
  
    config.vm.provision "shell", inline: <<-SHELL
      dnf update
      dnf upgrade -y
      dnf install -y wget vim net-tools gcc make tar git unzip sysstat tree
    SHELL
  end
  