---
- name: Provision Vagrant VM
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: Update and upgrade apt packages
    apt:
      update_cache: yes
      upgrade: 'dist'

  - name: Install necessary packages
    apt:
      name:
        - wget
        - vim
        - net-tools
        - gcc
        - make
        - tar
        - git
        - unzip
        - sysstat
        - tree
        - software-properties-common
        - docker.io
        - docker-compose
        - clang
        - lldb
        - llvm
        - openjdk-11-jdk
      state: latest

  # Add more tasks for your specific setup here...

  - name: Clean up apt cache
    apt:
      autoclean: yes
      autoremove: yes

  # Add additional roles or tasks as needed
