# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant Configuration for Development Environments

Vagrant.configure("2") do |config|
    # Define the base box for Ubuntu Server 22.04
    config.vm.box = "foundation/ubuntu-22-04"
    config.vm.box_version = "~> 1.1"
  
    # Define virtual machine name.
    config.vm.define "foundation-ubuntu-22-04-server"
  
    # Set virtual machine hostname.
    config.vm.hostname = "foundation-ubuntu-22-04-server"
  
    # Disable automatic box update checking.
    config.vm.box_check_update = false
  
    # Configure a private network with a dynamic IP.
    config.vm.network "private_network", type: "dhcp"
  
    # Enable and configure synced folders.
    config.vm.synced_folder ".", "/vagrant", disabled: false
  
    # SSH credentials to connect to virtual machine.
    config.ssh.username = "vagrant"
    config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
    config.ssh.insert_key = true  # Use Vagrant's automatic key insertion.
  
    # Provider-specific configuration for optimal performance.
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false  # Disable GUI when booting the virtual machine.
      vb.memory = "4096"  # Allocate more memory to the virtual machine for heavier workloads.
      vb.cpus = "2"  # Allocate more processors to the virtual machine for better performance.
      # Additional VirtualBox specific configurations can go here.
    end
  
    config.vm.provider "vmware_workstation" do |vwm|
      vwm.gui = false  # Disable GUI when booting the virtual machine.
      vwm.memory = "4096"  # Allocate more memory to the virtual machine for heavier workloads.
      vwm.cpus = "2"  # Allocate more processors to the virtual machine for better performance.
      # Additional VMware specific configurations can go here.
    end
  
    # Provisioning with Ansible.
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "update&upgrade_playbook.yml"
      ansible.verbose = "v"
      ansible.inventory_path = "inventory.ini"
      # Additional Ansible configurations can go here.
    end
  end
  