#!/usr/bin/env bash
# Vagrant Configuration for Alma Linux 9 Server

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jay-alexander-elliot/alma-linux-9"
  config.vm.box_version = "1.1.1"

  # Define virtual machine name.
  config.vm.define "jay-alexander-elliot-alma-linux-9-server"

  # Set virtual machine hostname.
  config.vm.hostname = "jay-alexander-elliot-alma-linux-9-server"

  # Disable automatic box update checking.
  config.vm.box_check_update = false

  # Forwarded port mapping configurations can be uncommented and modified as per requirement.
  # config.vm.network "forwarded_port", guest: 443, host: 443, auto_correct: false
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Private network configuration.
  config.vm.network "private_network", ip: "192.168.201.8"

  # Shared folder configuration.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # SSH configuration.
  config.ssh.username = "vagrant"
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  # Provider-specific configuration (example for VMware Fusion).
  config.vm.provider "vmware_fusion" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "1"
  end

  # Provisioning configuration.
  config.vm.provision "shell", inline: <<-SHELL
    dnf update -y
    dnf install -y wget vim net-tools initscripts gcc make tar bind-utils nc git unzip sysstat tree
  SHELL
end
