---
- name: Provision Vagrant VM
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: Update and upgrade pkg packages
    shell: pkg update && pkg upgrade -y
    args:
      warn: no

  - name: Install necessary packages
    pkgng:
      name:
        - wget
        - vim
        - net-tools
        - gcc
        - git
        - unzip
        - sysstat
        - tree
      state: latest

  # Add more tasks for your specific setup here...

  - name: Clean up pkg cache
    shell: pkg clean -y
    args:
      warn: no

  # Add additional roles or tasks as needed
