# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile - Rocky Linux 9 Configuration

Vagrant.configure("2") do |config|
  # Use the official Rocky Linux 9 Vagrant box
  config.vm.box = "rockylinux/9"
  config.vm.box_version = "3.0.0"

  # Define virtual machine name.
  config.vm.define "jay-alexander-elliot-rocky-linux-9-server"

  # Set virtual machine hostname.
  config.vm.hostname = "jay-alexander-elliot-rocky-linux-9-server"

  # Other configurations remain the same...
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.201.10"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.username = "vagrant"
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  # Provider-specific configuration (VMware Fusion)
  config.vm.provider "vmware_fusion" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "1"
  end

  # Provisioning with a shell script
  config.vm.provision "shell", inline: <<-SHELL
    dnf update -y
    dnf install -y wget vim net-tools initscripts gcc make tar bind-utils nc git unzip sysstat tree
  SHELL
end
