# -*- mode: ruby -*-
# vi: set ft=ruby :

# FreeBSD 13 Vagrant Configuration
Vagrant.configure("2") do |config|
  config.vm.box = "generic/freebsd13"
  config.vm.box_version = "4.3.10"

  # Define virtual machine name.
  config.vm.define "jay-alexander-elliot-freebsd13-server"

  # Set virtual machine hostname.
  config.vm.hostname = "jay-alexander-elliot-freebsd13-server"

  # Other configurations remain the same...

  # Provider-specific configuration for FreeBSD
  config.vm.provider "vmware_fusion" do |vb|
    # Disable GUI when booting the virtual machine.
    vb.gui = false
  
    # Allocate memory to the virtual machine.
    vb.memory = "2048"

    # Allocate processors to the virtual machine.
    vb.cpus = "1"
  end

  # Enable provisioning with a shell script. Adjusting for FreeBSD.
  config.vm.provision "shell", inline: <<-SHELL
    pkg update -y
    pkg install -y wget vim net-tools git unzip sysstat tree
  SHELL
end
